### ISSUE TITLE
Lab 4 "Execution failure in 'lookup': (TypeError)"

### ISSUE THREAD

**Issue by usamabinrauf** [MicrosoftLearning/mslearn-ai-studio#22]
# Lab: 04
### Description of issue:

I am getting the "**Execution failure in 'lookup': (TypeError) unsupported operand type(s) for +: 'NoneType' and 'int**'" after submitting the prompt as instructed in the step. When I submit the prompt multiple times, the error changes to "**Execution failure in 'chat_with_context': (TypeError) unsupported operand type(s) for +: 'NoneType' and 'NoneType'**'".

I have attached screenshot for your reference below.

### Screenshot:
![Screenshot_14](https://github.com/user-attachments/assets/2dd50b9f-c4d8-4fa9-afba-b6d5ff2a6191)

**Comment by afelix-95** [comment]
@ivorb I just tested this lab for MJ and got the same error. Looking at the online deployment log it says that the endpoint is trying to use a deprecated library (Pydantic) and method (dict), so it switches methods and doesn't recognize the token attributes needed to finish the run successfully. Since the prompt flow worked correctly in the compute session, it seems to be a product issue in the endpoint deployment only.

**Comment by ivorb** [comment]
thanks @usamabinrauf and @afelix-95 - given it's a product bug I'll add a note to exercise for now
